### ISSUE TITLE
set input in form and submit form but doesn't work

### ISSUE THREAD

**Issue by Parvaz19** [Pharaonic/livewire-tagify#2]
I set input in form and submit form but not work.

`<form id="form-tag" wire:submit.prevent="updateTags">
            <input data-pharaonic="tagify"  data-component-id="{{ $this->id }}" wire:model.defer="tags"
                class="w-100 py-2 bg-white px-2 form-control" pattern='^[A-Za-z_]{2,15}$'
                 data-max="3">
            <div class="d-flex flex-row justify-content-end">
                <button class="btn btn-warning p-0 px-1 elevation-1 mt-1 " type="submit">
                    <i class="fa fa-check-circle"></i>
                    <span>save</span>
                </button>
            </div>
        </form>`

and in component

`public function updateTags(){
        dd($this->tags);
    }`

by click on save button for submit form doesn't change any thing and doesn't send any request to backend.
hwo can I solve this problem?

**Comment by RaggiTech** [comment]
Hello @Parvaz19 

Just remove this pattern attribute `pattern='^[A-Za-z_]{2,15}$'` 👍🏻

**Comment by MoamenEltouny** [comment]
Hello @Parvaz19

Just remove the pattern attribute `pattern='^[A-Za-z_]{2,15}$'` 👍🏻

**Comment by Parvaz19** [comment]
thanks @RaggiTech 

then how can I define pattern for tags in input?

**Comment by MoamenEltouny** [comment]
@Parvaz19 it's not supported right now will work on it soon
