### ISSUE TITLE
Tagify is not defined

### ISSUE THREAD

**Issue by eafarooqi** [Pharaonic/livewire-tagify#3]
getting the error in browser console
Uncaught ReferenceError: Tagify is not defined

JS file is loaded correctly. 
<script src="{{ asset('vendor/pharaonic/pharaonic.tagify.min.js') }}"></script>

tried with option 1 as well, same results.

**Comment by MoamenEltouny** [comment]
Hello @eafarooqi 
Did you include the Tagify plugin js file too?

**Comment by eafarooqi** [comment]
Hi, 
I have followed documentation, and in documentation there is only js file. The plugin assets files suppose to be inside the package assets or should be specifically stated in documentation.

**Comment by MoamenEltouny** [comment]
Okay. Sorry for that, I'm already developing all of docs to be more detailed.
