### ISSUE TITLE
Correct format for setting value?

### ISSUE THREAD

**Issue by MCKLtech** [Pharaonic/livewire-tagify#4]
I'm following the read me as [outlined here](https://pharaonic.io/packages/livewire/tagify/1.x/usage) but I'm getting some unexpected behaviour.

For example, this:

```
public function mount()
{
  $this->tags = ['Apple', 'Banana'];
}

<input data-pharaonic="tagify"data-component-id="{{$this->id}}" wire:model="tags">

```
Initially works but when I add a new tag, the front end field collapses to:

`[{"value":"[object Object]"}]`

Likewise, it seems the $tags parameter is updated to this format:

```
[
    [
        "value" => "Apple"
    ],
    [
        "value" => "Banana"
    ]
]
```

I then tried it by setting the $tags parameter to an empty array, and using the value:

`<input data-pharaonic="tagify" data-component-id="{{$this->id}}"  wire:model="tags" value='@json(['Apple', 'Banana'])'>`

But this has the same issue.

Any pointers?

**Comment by manusiakemos** [comment]
try add data-direct attribute

**Comment by MCKLtech** [comment]
Thanks, @manusiakemos but the issue persists.

**Comment by MoamenEltouny** [comment]
@manusiakemos Thank you so much for trying to help.

@MCKLtech 

1. Livewire is updating the DOM  so you have to use ``` wire:ignore``` with ```data-direct``` if you will not manipulate the values on the component side.
```html
<div wire:ignore>
    <input data-pharaonic="tagify" id="tags" data-component-id="{{$this->id}}" wire:model="tags" data-direct>
</div>
```
2. And you can use ```wire:model.defer="tags"``` if you want to keep the current DOM as it till next request.

3. If you want to inject Tagify to this input every single request it's not the best idea but you can do it by adding an id to the input and load the tagify on this input with some lines like : 
```php
public function hydrateTags()
{
    $this->dispatchBrowserEvent('pharaonic.tagify.load', [
        'target' => '#tags',
        'component' => $this->id
    ]);
}
```

**Comment by MCKLtech** [comment]
@MoamenEltouny , can you post a full example with a Livewire controller? Unless I'm missing something, I feel this library has a bug, or otherwise, the documentation is incorrect.

I tried all your various suggestions and my example above still does not work. Any time I update, the tag array is reformatted to the ['value' => 'xyz'] format, and breaks on the front end.

In simple terms, how can I set an array in Livewire, present this on the front end, add a tag or two there, and when I save it on the Livewire controller those values available?

Edit, this is working but I feel it should probably be documented as, to me, the docs make it sound like you don't need this:

`<div wire:ignore>
                                <input data-pharaonic="tagify"
                                       data-component-id="{{$this->id}}"
                                       wire:model="tags"
                                       data-suggest-list='{{json_encode($suggestions)}}'
                                       data-suggest
                                       data-direct
                                >
                            </div>`

**Comment by MoamenEltouny** [comment]
@MCKLtech Okay i will work on adding ```wire:ignore``` to the documentation
