### ISSUE TITLE
how to use options from the Tagify to open dropdown on focus

### ISSUE THREAD

**Issue by eafarooqi** [Pharaonic/livewire-tagify#5]
Hi, 

is there a way to use tagify options. i wanted to show the dropdown on focus. There is one option ` enabled: 0` how can i implement that. or any other way to open the dropdown on focus. Thanks

```
dropdown: {
        enabled: 0,             // <- show suggestions on focus
        closeOnSelect: false    // <- do not hide the suggestions dropdown once an item has been selected
      }
```

**Comment by MoamenEltouny** [comment]
**can you explain more about your issue ?**
