### ISSUE TITLE
How to use on dynamically loaded field

### ISSUE THREAD

**Issue by jordanade** [Pharaonic/livewire-tagify#6]
My tagify field is itself loaded dynamically via livewire. Is there a way to trigger reinitialization upon livewire's render or is there a better way to handle this?

**Comment by MoamenEltouny** [comment]
Hi @jordanade 
i believe that you are asking about the event that helps to reload a specific tagify input, am i right?

```
$this->dispatchBrowserEvent('pharaonic.tagify.load', [
    'component' => $this->id,
    'target' => '#tags'
]);
```

**Comment by jordanade** [comment]
Thank you @MoamenEltouny.
I made my own browser event that called `Pharaonic.Tagify.init()` which seemed to work as well. I'll switch to your method.
